package uk.gav;

import java.util.GregorianCalendar;
import java.util.regex.Pattern;

public class EmailContentProcessor extends ContentProcessor {

	private final static String  patternString = "%%.*?%%";
	private final static Pattern repPattern = Pattern.compile(patternString);
	
	private EventEmailContent cont;
		
	public static void main(String[] args) {
		EmailContentProcessor processor = new EmailContentProcessor();
		EventEntity ee = new EventEntity();
		ee.setEventContent("{\"to\":\"gavlad@bad.com\",\"subject\":\"Lav It\", \"contentType\":\"one\",\"version\":1.0}");
		EventEmailContent eec = new EventEmailContent(ee);
		eec.setTo(new String[] {"gav@lad.com"});
		processor.setEventEmailContent(eec);
		processor.processContent("Hello %%to%%\nHow are you doing. This email was generated by GEN :-) on %%today%%\n");
	}
	
	public EmailContentProcessor() {
		this.setReplacementRegEx(repPattern);
	}
	
	public void setEventEmailContent(EventEmailContent cont) {
		this.cont = cont;
	}
	
	@Override
	public String replaceField(String regEx) {
		String output = regEx;
		if ("%%to%%".equals(regEx)) {
			if (cont != null) {
				output =  cont.getTo()[0];
			}
		}
		else if ("%%today%%".equals(regEx)) {
			output = GregorianCalendar.getInstance().getTime().toString();
		}
		
		return output;
	}

}
